import React, { Component, ErrorInfo, ReactNode, useState } from 'react';
import { CheckCircle2, Zap } from 'lucide-react';
import { supabase } from '../lib/supabase';

export function ResetPasswordPage() {
  const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (password.length < 8) return setMessage('Use at least 8 characters.'); if (password !== confirm) return setMessage('Passwords do not match.'); if (!supabase) return setMessage('Authentication is not configured.'); setBusy(true); const { error } = await supabase.auth.updateUser({ password }); setBusy(false); setMessage(error ? error.message : 'Password updated. You can now return to PowerSense and sign in.'); };
  return <main className="min-h-screen grid place-items-center bg-slate-950 p-5 text-slate-100"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-slate-800 bg-slate-900 p-8 shadow-2xl space-y-5"><Zap className="text-cyan-400"/><div><h1 className="text-2xl font-bold">Create a new password</h1><p className="mt-1 text-sm text-slate-400">Secure your PowerSense account.</p></div><input required type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="New password" className="w-full rounded-xl border border-slate-700 bg-slate-950 p-3 outline-none focus:border-cyan-400"/><input required type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirm password" className="w-full rounded-xl border border-slate-700 bg-slate-950 p-3 outline-none focus:border-cyan-400"/><button disabled={busy} className="w-full rounded-xl bg-cyan-400 py-3 font-bold text-slate-950">{busy ? 'Updating…' : 'Update password'}</button>{message && <p className="text-sm text-cyan-200">{message}</p>}</form></main>;
}

export class AppErrorBoundary extends Component<{children: ReactNode},{failed:boolean}> { state={failed:false}; static getDerivedStateFromError(){ return {failed:true}; } componentDidCatch(_error:Error,_info:ErrorInfo){} render(){ return this.state.failed ? <main className="min-h-screen grid place-items-center bg-slate-950 p-6 text-center text-white"><div><CheckCircle2 className="mx-auto mb-4 text-cyan-400"/><h1 className="text-2xl font-bold">PowerSense needs a refresh</h1><p className="mt-2 text-slate-400">Your data is safe. Reload this page to restore the workspace.</p><button onClick={()=>location.reload()} className="mt-6 rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">Reload PowerSense</button></div></main> : this.props.children; } }
