import React, { useState } from 'react';
import {
  Lightbulb,
  CheckCircle2,
  Clock,
  DollarSign,
  TrendingDown,
  Sparkles,
  Zap,
  Check,
  Sun,
  Flame,
  Wrench,
  Filter,
} from 'lucide-react';
import { api } from '../services/api';
import { Recommendation } from '../types';

interface RecommendationsProps {
  recommendations: Recommendation[];
  analysisState?: string | null;
  onOpenProfile: () => void;
  onRecommendationUpdate: (updated: Recommendation) => void;
}

export const Recommendations: React.FC<RecommendationsProps> = ({
  recommendations,
  analysisState,
  onOpenProfile,
  onRecommendationUpdate,
}) => {
  const [selectedCategory, setSelectedCategory] = useState<string>('All');

  const categories = [
    'All',
    'HVAC & Cooling',
    'Behavioral Shifting',
    'Appliance Upgrade',
    'Solar & Net Metering',
  ];

  const filtered = selectedCategory === 'All'
    ? recommendations
    : recommendations.filter((r) => r.category === selectedCategory);

  const totalSavingsPotential = recommendations.reduce((acc, r) => acc + r.estimatedMonthlySavings, 0);
  const totalKwhSavings = recommendations.reduce((acc, r) => acc + r.estimatedKwhSavings, 0);

  const handleStatusToggle = async (id: string, currentStatus: string) => {
    const nextStatus = currentStatus === 'completed' ? 'new' : 'completed';
    try {
      const updated = await api.updateRecommendationStatus(id, nextStatus);
      onRecommendationUpdate(updated);
    } catch (err: any) {
      console.error('Failed to update status:', err);
    }
  };

  return (
    <div className="space-y-8 pb-12">
      {/* Header */}
      <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 lg:p-8 flex flex-col md:flex-row items-start md:items-center justify-between gap-6 shadow-xl">
        <div className="space-y-2">
          <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-semibold">
            <Sparkles className="w-3.5 h-3.5" />
            <span>AI Energy Optimization & Action Plan Engine</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white">
            Personalized Energy Saving Recommendations
          </h1>
          <p className="text-xs text-slate-400 max-w-2xl">
            Custom actionable guides generated by analyzing your electricity bill OCR trends, appliance power profiles, and peak tariff schedules.
          </p>
        </div>

        {/* Savings Summary Badge */}
        <div className="p-4 bg-slate-950 border border-emerald-500/30 rounded-2xl space-y-1 text-right">
          <p className="text-[10px] text-slate-400 uppercase tracking-wider font-semibold">Total Monthly Savings Potential</p>
          <p className="text-2xl font-black text-emerald-400 font-mono">₹{totalSavingsPotential.toFixed(2)} <span className="text-xs font-normal text-slate-400">/mo</span></p>
          <p className="text-[11px] text-cyan-400 font-mono font-bold">-{totalKwhSavings} kWh / Month Reduction</p>
        </div>
      </div>

      {/* Category Filter Pills */}
      <div className="flex flex-wrap items-center gap-2 border-b border-slate-800 pb-4">
        <span className="text-xs text-slate-400 font-semibold mr-2 flex items-center space-x-1">
          <Filter className="w-3.5 h-3.5 text-cyan-400" />
          <span>Category Filter:</span>
        </span>
        {categories.map((cat) => (
          <button
            key={cat}
            onClick={() => setSelectedCategory(cat)}
            className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all ${
              selectedCategory === cat
                ? 'bg-cyan-500 text-slate-950 font-bold shadow-md shadow-cyan-500/20'
                : 'bg-slate-900 border border-slate-800 text-slate-300 hover:bg-slate-800'
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Recommendation Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {filtered.length === 0 && <div className="md:col-span-2 rounded-2xl border border-amber-500/30 bg-slate-900 p-8 text-center text-xs text-slate-300 space-y-3"><p>{analysisState || 'No recommendations were saved for the active bill.'}</p>{analysisState?.startsWith('No trained-model') && <button onClick={onOpenProfile} className="px-3 py-2 rounded-lg bg-cyan-500 text-slate-950 font-bold">Complete Profile</button>}</div>}
        {filtered.map((rec) => (
          <div
            key={rec.id}
            className={`bg-slate-900 border rounded-3xl p-6 space-y-4 transition-all relative overflow-hidden flex flex-col justify-between ${
              rec.status === 'completed'
                ? 'border-emerald-500/40 opacity-80 bg-slate-950/60'
                : 'border-slate-800 hover:border-cyan-500/40'
            }`}
          >
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-bold px-2.5 py-0.5 rounded-full uppercase bg-cyan-500/10 text-cyan-300 border border-cyan-500/20">
                  {rec.category}
                </span>

                <span
                  className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase ${
                    rec.impactLevel === 'High'
                      ? 'bg-rose-500/15 text-rose-400'
                      : 'bg-amber-500/15 text-amber-300'
                  }`}
                >
                  {rec.impactLevel} Impact
                </span>
              </div>

              <h3 className="text-base font-bold text-white leading-snug">{rec.title}</h3>
              <p className="text-xs text-slate-300 leading-relaxed">{rec.description}</p>
            </div>

            <div className="pt-4 border-t border-slate-800/80 space-y-3">
              <div className="grid grid-cols-3 gap-2 text-center text-xs">
                <div className="p-2 bg-slate-950 rounded-xl border border-slate-800">
                  <p className="text-[10px] text-slate-400">Monthly Savings</p>
                  <p className="font-mono font-bold text-emerald-400">₹{rec.estimatedMonthlySavings}</p>
                </div>

                <div className="p-2 bg-slate-950 rounded-xl border border-slate-800">
                  <p className="text-[10px] text-slate-400">kWh Reduction</p>
                  <p className="font-mono font-bold text-cyan-400">{rec.estimatedKwhSavings} kWh</p>
                </div>

                <div className="p-2 bg-slate-950 rounded-xl border border-slate-800">
                  <p className="text-[10px] text-slate-400">Est. Cost</p>
                  <p className="font-mono font-semibold text-slate-200">{rec.implementationCost}</p>
                </div>
              </div>

              <button
                onClick={() => handleStatusToggle(rec.id, rec.status)}
                className={`w-full py-2.5 rounded-xl font-bold text-xs transition-all flex items-center justify-center space-x-2 ${
                  rec.status === 'completed'
                    ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40'
                    : 'bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700'
                }`}
              >
                <Check className="w-4 h-4" />
                <span>{rec.status === 'completed' ? 'Marked as Done (Applied)' : 'Mark as Applied'}</span>
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
